# https://docs.vmware.com/en/VMware-Tanzu-SQL-with-Postgres-for-Kubernetes/1.4/tanzu-postgres-k8s/GUID-backup-restore.html
---
apiVersion: sql.tanzu.vmware.com/v1
kind: PostgresBackupLocation
metadata:
  name: backuplocation-sample
spec:
  storage:
    s3:
      bucket: "minio"
      bucketPath: "/velero-highgarden"
      region: "highgarden"
      endpoint: "highgarden.gorke.ml"
      forcePathStyle: false
      enableSSL: true
      secret:
        name: backuplocation-creds-sample

---
apiVersion: v1
kind: Secret
metadata:
  name: backuplocation-creds-sample
type: generic
stringData:
  accessKeyId: "admin"
  secretAccessKey: "rOORFtozTuCycOuQkEgIoCM3sYMwCqznmgDBN0ew"