# https://docs.vmware.com/en/VMware-Tanzu-SQL-with-Postgres-for-Kubernetes/1.4/tanzu-postgres-k8s/GUID-backup-restore.html
---
apiVersion: sql.tanzu.vmware.com/v1
kind: PostgresBackup
metadata:
  name: backup-sample1
spec:
  sourceInstance:
    name: postgres-sample
  type: full