apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-istio-cluster-issuer
spec:
  acme:
    email: gorkemo@vmware.com
    preferredChain: ""
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: acme-gns
  name: acme-ingress-cert
  namespace: istio-system
spec:
  dnsNames:
  - acme.essos.gorke.ml
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-istio-cluster-issuer
  secretName: acme-ingress-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-pass
  namespace: acme-gns
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-mongo-pass
  namespace: acme-gns
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-mongo-pass
  namespace: acme-gns
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: users-mongo-pass
  namespace: acme-gns
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: shopping
  namespace: acme-gns
  labels:
    app: shopping
    service: shopping
spec:
  ports:
    - name: http-shopping
      protocol: TCP
      port: 3000
  selector:
    app: shopping
    service: shopping
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: shopping
  namespace: acme-gns
  labels:
    app: shopping
    service: shopping
spec:
  selector:
    matchLabels:
      app: shopping
      service: shopping
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping
        service: shopping
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-front-end:rel1
        name: shopping
        env:
        - name: FRONTEND_PORT
          value: '3000'
        - name: USERS_HOST
          value: 'users.example.com'
        - name: CATALOG_HOST
          value: 'catalog.example.com'
        - name: ORDER_HOST
          value: 'order.example.com'
        - name: CART_HOST
          value: 'cart.example.com'
        - name: USERS_PORT
          value: '8081'
        - name: CATALOG_PORT
          value: '8082'
        - name: CART_PORT
          value: '5000'
        - name: ORDER_PORT
          value: '6000'
        ports:
        - containerPort: 3000
          name: http-shopping
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acme-gateway
  namespace: acme-gns
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: acme-ingress-cert # must be the same as secret
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acme
  namespace: acme-gns
spec:
  hosts:
  - "acme.essos.gorke.ml"
  gateways:
  - acme-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: shopping
        port:
          number: 3000