apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-istio-cluster-issuer
spec:
  acme:
    email: gorkemo@vmware.com
    preferredChain: ""
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: acme-gns
  name: acme-ingress-cert
  namespace: istio-system
spec:
  dnsNames:
  - CHANGEMEACMEFQDN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-istio-cluster-issuer
  secretName: acme-ingress-cert
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acme-gateway
  namespace: acme-gns
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: acme-ingress-cert # must be the same as secret
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acme
  namespace: acme-gns
spec:
  hosts:
  - "CHANGEMEACMEFQDN"
  gateways:
  - acme-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 3000