---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder-java-harbor
spec:
  serviceAccount: dockerhub-service-account
  tag: harbor.dorn.gorky.ml/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder-node-harbor
spec:
  serviceAccount: dockerhub-service-account
  tag: harbor.dorn.gorky.ml/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs