apiVersion: v1
data:
  .dockerconfigjson: CHANGEMEAUTHBASE64
kind: Secret
metadata:
  creationTimestamp: null
  name: tanzu-reg-cred
  namespace: rabbitmq
type: kubernetes.io/dockerconfigjson
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-reg-cred       # must match source secret name
  namespace: rabbitmq  # must match source secret namespace
spec:
  toNamespaces:
  - "*"  # star means export is available for all namespaces
