
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: nginx-deployment
  name: nginx-cert
  namespace: developer
spec:
  dnsNames:
  - nginx.highgarden.gorke.ml
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  secretName: nginx-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    projectcontour.io/websocket-routes: /
  labels:
    app: nginx-web
  name: nginx-web
  namespace: developer
spec:
  rules:
  - host: nginx.highgarden.gorke.ml
    http:
      paths:
      - backend:
          service:
            name: nginx-deployment
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nginx.highgarden.gorke.ml
    secretName: nginx-cert
---
